[package]
name = "magic_quickstart"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
dotenv = "0.15.0"
humantime = "2.1.0"
reqwest = { version = "0.12", features = ["json"] }
rev_lines = "0.3.0"
serde_json = "1.0.138"
tokio = { version = "1", features = ["full"] }
